### ISSUE TITLE
Please add a licence

### ISSUE THREAD

**Issue by secretshardul** [mozz100/bardofavon#1]
Greetings and thanks for building this project. I came across your repo from the [Open-Source-Shakespeare](https://github.com/edent/Open-Source-Shakespeare) project.

I want to use your normalized `.sql` file for an hackathon, but the absence of an open source licence is preventing me from doing so. Can you please add one? I'll be citing your repo in my submission.

**Comment by mozz100** [comment]
Done!  I followed @edent - from whom I originally got the data - and added "The Unlicense".

If you like Shakespeare and databases, check out https://www.rmorrison.net/shakespeare/

```
-- of all Shakespeare's characters, whose paragraphs/speeches are the longest, on average? 
SELECT 
  characters.name AS character_name, 
  SUM(length(paragraphs.plain_text)) as letter_count, 
  COUNT(*) as paragraph_count, 
  ROUND(SUM(length(paragraphs.plain_text))/COUNT(*), 2) as avg_speech_length 
FROM paragraphs 
 
INNER JOIN characters ON paragraphs.character_id = characters.id 
 
GROUP BY characters.name 
ORDER BY avg_speech_length DESC 
LIMIT 10;
```

and so on

**Comment by secretshardul** [comment]
Awesome! 🚀
